name: Hetzner Image Build
description: Builds a snapshot image on the Hetzner cloud
inputs:
  template:
    description: Path to template file
    required: true
  token:
    description: Token used to access Hetzner API
    required: true
  build-identifier:
    description: Content of build label attached to every instance and ssh-key for identifying resources (for cleanup)
    required: true
  iso-path:
    description: Path to local ISO file
    required: false
  server-location:
    description: Hetzner server location (e.g., nbg1, fsn1, hel1)
    required: false
  server-type:
    description: Hetzner server type (e.g., cx23, cx33, cx43)
    required: false
  vyos-customization-version:
    description: VyOS customization package version used in the ISO
    required: false
  release-version:
    description: Release version (e.g., 1.0.0). If provided, marks the snapshot as a release with protected=true label.
    required: false
  trigger-payload:
    description: Payload provided by workflow trigger
    required: false
runs:
  using: composite
  steps:
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      shell: bash
      run: |
        packer init ${{ inputs.template }}

    - name: Run `packer validate`
      id: validate
      shell: bash
      run: |
        echo "Processing payload..."
        payload='${{ inputs.trigger-payload }}'

        if [[ "${payload}" != "null"  ]]; then
          additional_vars=$(echo "$payload" | jq -r 'to_entries | map("-var \(.key)=\(.value)") | join(" ")')
          echo "Adding additional settings: ${additional_vars}"
        fi

        # Add ISO path if provided
        iso_path_var=""
        if [[ -n "${{ inputs.iso-path }}" ]]; then
          iso_path_var="-var vyos_iso_path=${{ inputs.iso-path }}"
          echo "Using local ISO: ${{ inputs.iso-path }}"
        fi

        # Add server location if provided
        location_var=""
        if [[ -n "${{ inputs.server-location }}" ]]; then
          location_var="-var server_location=${{ inputs.server-location }}"
          echo "Using server location: ${{ inputs.server-location }}"
        fi

        # Add server type if provided
        server_type_var=""
        if [[ -n "${{ inputs.server-type }}" ]]; then
          server_type_var="-var server_type=${{ inputs.server-type }}"
          echo "Using server type: ${{ inputs.server-type }}"
        fi

        # Add customization version if provided
        customization_version_var=""
        if [[ -n "${{ inputs.vyos-customization-version }}" ]]; then
          customization_version_var="-var vyos_customization_version=${{ inputs.vyos-customization-version }}"
          echo "Using VyOS customization version: ${{ inputs.vyos-customization-version }}"
        fi

        # Add release version if provided
        release_version_var=""
        if [[ -n "${{ inputs.release-version }}" ]]; then
          release_version_var="-var release_version=${{ inputs.release-version }}"
          echo "Using release version: ${{ inputs.release-version }}"
          echo "This snapshot will be marked as PROTECTED"
        fi

        packer validate \
          -var hcloud_token=${{ inputs.token }} \
          -var build_identifier=${{ inputs.build-identifier }} \
          $additional_vars \
          $iso_path_var \
          $location_var \
          $server_type_var \
          $customization_version_var \
          $release_version_var \
          ${{ inputs.template }}

    - name: Run `packer build`
      shell: bash
      run: |
        echo "Processing payload..."
        payload='${{ inputs.trigger-payload }}'

        if [[ "${payload}" != "null" ]]; then
          additional_vars=$(echo "$payload" | jq -r 'to_entries | map("-var \(.key)=\(.value)") | join(" ")')
          echo "Adding additional settings: ${additional_vars}"
        fi

        # Add ISO path if provided
        iso_path_var=""
        if [[ -n "${{ inputs.iso-path }}" ]]; then
          iso_path_var="-var vyos_iso_path=${{ inputs.iso-path }}"
          echo "Using local ISO: ${{ inputs.iso-path }}"
        fi

        # Add server location if provided
        location_var=""
        if [[ -n "${{ inputs.server-location }}" ]]; then
          location_var="-var server_location=${{ inputs.server-location }}"
          echo "Using server location: ${{ inputs.server-location }}"
        fi

        # Add server type if provided
        server_type_var=""
        if [[ -n "${{ inputs.server-type }}" ]]; then
          server_type_var="-var server_type=${{ inputs.server-type }}"
          echo "Using server type: ${{ inputs.server-type }}"
        fi

        # Add customization version if provided
        customization_version_var=""
        if [[ -n "${{ inputs.vyos-customization-version }}" ]]; then
          customization_version_var="-var vyos_customization_version=${{ inputs.vyos-customization-version }}"
          echo "Using VyOS customization version: ${{ inputs.vyos-customization-version }}"
        fi

        # Add release version if provided
        release_version_var=""
        if [[ -n "${{ inputs.release-version }}" ]]; then
          release_version_var="-var release_version=${{ inputs.release-version }}"
          echo "Using release version: ${{ inputs.release-version }}"
          echo "This snapshot will be marked as PROTECTED"
        fi

        packer build \
          -color=false \
          -force \
          -on-error=cleanup \
          -var hcloud_token=${{ inputs.token }} \
          -var build_identifier=${{ inputs.build-identifier }} \
          $additional_vars \
          $iso_path_var \
          $location_var \
          $server_type_var \
          $customization_version_var \
          $release_version_var \
          ${{ inputs.template }}
